version: "3.8"

services:
  hedsql:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=heduser
      - POSTGRES_PASSWORD=hedpassword
      - POSTGRES_DB=heddb